[service]
    host = "localhost"
    port = 8998
    secret = "//"

[utm]
    # list of connected billings
    [utm.test]
        addr = "192.168.122.168:11758"
        cert = "urfa.crt"

    [utm.tv]
        addr = "192.168.28.135:11758"
        cert = "urfa.crt"
